---
title: "Average Weekly Temperature - CMAR Data" 
author: Danielle Dempsey 
format: 
  html: 
    toc: true 
    toc-depth: 3 
embed-resources: true
dpi: 600 
echo: false
editor_options:
  chunk_output_type: console
---

```{r}
#| include: false

library(dplyr)
library(data.table)
library(ggplot2)
library(htmltools)
library(lubridate)
library(plotly)
library(purrr)

# ensures the Plotly JS dependencies are loaded being called in the loop
htmltools::tagList(plot_ly(x = rnorm(10), type = "histogram"))

theme_set(theme_light())
theme_facet_plotly <- theme(panel.spacing.y = unit(5, "lines"))

path <- "/home/jovyan/shared-public/ohw26/model_downsampling/"

files <- list.files(path, full.names = TRUE, pattern = "cmar_temperature")

dat_raw <- map(files, fread, 
               colClasses = c("character", "numeric", "numeric", "numeric",
                              "POSIXct", "numeric", "numeric", "character")) %>% 
  list_rbind() %>% 
  mutate(
    iso_year = isoyear(timestamp_utc),   
    iso_week = isoweek(timestamp_utc),
    year_week = paste(iso_year, "_", iso_week)
  )

dat <- dat_raw %>% 
  summarise(
    mean_temperature = mean(temperature_degree_c),
    n = n(),
  .by = c(station, sensor_depth_at_low_tide_m, iso_year, iso_week)
  ) %>% 
  mutate(
     depth_m = ordered(
      sensor_depth_at_low_tide_m, levels = sort(unique(dat_raw$sensor_depth_at_low_tide_m))
    )
  )

```

# Quick Check: Number of Observations

Boxplot of number of observations in each station, year, week, and depth combo.

```{r}

p <- ggplot(dat, aes(depth_m, n)) +
  geom_boxplot() +
  facet_wrap(~station, scales = "free", ncol = 3) +
  theme_facet_plotly

ggplotly(p, height = 500)

```


# View Weekly Averages

```{r}
#| results: asis

stations <- unique(dat$station)

for(i in seq_along(stations)) {
  station_i <- stations[i]
  
  cat('\n###', station_i, '\n')
  
  dat_i <- dat %>% 
    filter(station == station_i) 
  
  p <- ggplot(dat_i, aes(iso_week, mean_temperature, colour = depth_m)) +
    geom_point() +
    facet_wrap(~iso_year, ncol = 1)
  
  n_year <- length(unique(dat_i$iso_year))
  
  if(n_year == 1) {
    h <- 175
  } else h <- n_year * 120
  # if(n_year <= 3) h <- 250
  # if(n_year > 3) h <- 500
  
  print(htmltools::tagList(ggplotly(p, height = h)))
}

```



```{r}
# uncomment to export
#fwrite(dat, paste0(path, "cmar_weekly_average_temperature.csv"))
```
````
